import { ProductRecord } from "./supabase.js";

export const SEED_PRODUCTS_MAP: Record<string, ProductRecord> = {
  "prod-1": {
    product_id: "prod-1",
    id: "prod-1",
    artisan_id: "seed-artisan-ramesh",
    title: "Hand-painted Terracotta Clay Vase",
    description: "Molela terracotta clay craft is an ancient ritual craft from Rajasthan. Clay dug from the Banas river is kneaded by foot with rice husk and binder.",
    category: "pottery",
    category_label: "Handmade Terracotta",
    materials: ["Banas River Clay", "Natural Ochre Slip", "Vegetable Gum Binder"],
    dimensions: "10 inch height × 5.5 inch diameter, 850g",
    tags: ["terracotta", "pottery", "clay", "diwali", "vase", "home-decor"],
    price: 1850,
    stock: 14,
    status: "published",
    images: [
      {
        image_id: "img-prod-1",
        id: "img-prod-1",
        product_id: "prod-1",
        image_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuBs5bp8EhpGMkFW42TorHnIKCSon5Xasq4s8ZRGaZ_rT2fPvKlc4bHVGR2K6GSQFENT7iWt7wl3Z0nDHiTqawnmzMq93Htdek73P6gJtbF13zWRvU7Ye1VtgCFb-rU6R1NGFAn2axMfAa3Ku31tq_lKTrxZGKyDa1gJxVw0sg5SsEDLyTGIDXYmMIYay48tz3ojBv66HClVmc_QActkv8rvg1CvLR2FOEbpV1FBKMo94_F9aNlw4XyQGQ",
        image_type: "original",
        is_primary: true,
      },
    ],
  },
  "prod-2": {
    product_id: "prod-2",
    id: "prod-2",
    artisan_id: "seed-artisan-shanti",
    title: "Royal Blue Chanderi Zari Saree",
    description: "Chanderi weaving dates back to the Vedic era and flourished under Mughal patronage with pure metallic gold zari motifs.",
    category: "textiles",
    category_label: "Chanderi Handloom",
    materials: ["Degummed Mulberry Silk", "Long Staple Cotton", "Tested Metallic Zari"],
    dimensions: "5.5m length + 0.8m blouse piece, 420g",
    tags: ["saree", "chanderi", "silk", "handloom", "wedding", "festive"],
    price: 6450,
    stock: 2,
    status: "published",
    images: [
      {
        image_id: "img-prod-2",
        id: "img-prod-2",
        product_id: "prod-2",
        image_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBMEf7i5Od9i2OqXdjAmP2ysbETHlacsxax4gbZALwquDf_pUzFLTzBvvysCE3xuPyGbJB8d4esMmRxsQUHVl_Bug77ruFTbEBGG_7WjL5BxRylpqABP9LmNdNuKet0aMtZ_oNOdZFGHn9NA4BGSygoYUFLCwnu047SgEsBI8TASFAMpoD_-tTeOrOZsFnuwwBDLAnTBEKpBTN_znMuBNHl5V-yd04-xq_qR0XZ8Az_IJaW0Ob2KSe5g",
        image_type: "original",
        is_primary: true,
      },
    ],
  },
  "prod-3": {
    product_id: "prod-3",
    id: "prod-3",
    artisan_id: "seed-artisan-kiran",
    title: "Handcrafted Dhokra Brass Figurine",
    description: "Dhokra lost-wax casting artifact of rural musicians with clay core wrapped in fine beeswax coils before bronze molten pouring.",
    category: "brass",
    category_label: "Brass & Metal Craft",
    materials: ["Recycled Brass & Bronze", "Beeswax Wire", "Riverbed Red Mud Core"],
    dimensions: "7.5 inch height × 4.2 inch width, 1.2kg",
    tags: ["dhokra", "brass", "tribal", "sculpture", "antique", "metal"],
    price: 3200,
    stock: 8,
    status: "published",
    images: [
      {
        image_id: "img-prod-3",
        id: "img-prod-3",
        product_id: "prod-3",
        image_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBe5TziQ6gu_huzgkSzTl4P1iZ9H6v2hnv9MqENoOb_cb8AZIOCfSDX3ZhFkrzMv5XCc41XDqsHKL1alpbCQlMCsrWp3U8Q2k00tumPNj6HkhTr1uGox7RdkX3wf2KAIPMF2Hy5ko7QDWRrw-r9NlHxsWAeJP0zasjMenfnBff3rZjJrSYW51ZKF8rLh52OZu4D4lTfKGLqg0_52plxXfU2G32tg_znysgbD0NpdhvCuxyljrthQLUCQ",
        image_type: "original",
        is_primary: true,
      },
    ],
  },
  "prod-4": {
    product_id: "prod-4",
    id: "prod-4",
    artisan_id: "seed-artisan-manoj",
    title: "Carved Sheesham Wood Spice Box",
    description: "Sheesham rosewood spice box with hand-carved floral patterns, geometric Mughal jali screens, and pure sheet brass latch.",
    category: "wood",
    category_label: "Wood Carving",
    materials: ["Seasoned Indian Rosewood (Sheesham)", "Solid Sheet Brass", "Natural Linseed Oil Polish"],
    dimensions: "8 × 8 × 2.5 inches, 9 compartments, 750g",
    tags: ["wood", "sheesham", "kitchen", "spicebox", "carving", "handcrafted"],
    price: 1450,
    stock: 11,
    status: "published",
    images: [
      {
        image_id: "img-prod-4",
        id: "img-prod-4",
        product_id: "prod-4",
        image_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuArCKBkyuC6dsvyRjTL0Bmkeo_U_9om6-tNpVNuE6EtbnjXB5KVhmHlWzB8fCjVWXykvEKbnRv0d-H65_QRKz30bmhj3LxslLA6Az3BwNEWYeRyvHbu33hflFZTTEFyv4Fbsnt6GKMwSM6eADwTuWH6dJLqlS0qWy0aygGDpmmR3UyJ_YNsW0LmjVfgG7dZbfZcG9vSEi2VyAxwja1Pd9kwmlTdRhuoHnl8PzbqNaJZKcZl-cGj7ghwag",
        image_type: "original",
        is_primary: true,
      },
    ],
  },
  "prod-5": {
    product_id: "prod-5",
    id: "prod-5",
    artisan_id: "seed-artisan-anita",
    title: "Glazed Ceramic Chai Kulhad Set (6 pcs)",
    description: "Traditional Khurja Kulhads feature botanical mineral slips and are double-fired at 1200°C, microwave safe and food grade.",
    category: "pottery",
    category_label: "Studio Pottery",
    materials: ["High-fire Stoneware Clay", "Natural Cobalt & Iron Slips", "Food-grade Lead-free Glaze"],
    dimensions: "Set of 6, 180 ml capacity each, 1.1kg total",
    tags: ["chai", "kulhad", "ceramic", "tea", "cups", "pottery"],
    price: 899,
    stock: 1,
    status: "published",
    images: [
      {
        image_id: "img-prod-5",
        id: "img-prod-5",
        product_id: "prod-5",
        image_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuB4zbcaSORQar69cY4hUI1hrEKJwFal25MxfQKtcDGmCUqAQpJubJx9frH3jqSisAfUZS9R7HHfl_bVtcFOBIqIqUeu7zTCBuP52MiVi1Xs5PE0XN3SDJrBcxrFi6dnodpJkNiWTZD0p9FeGUWNFXoJzoa0zcVZGmWpo8LYntcbcISiFdz-a6BYALK6DF3FnukSEZYwr_sdNE9TZtO2Ics_tMv5HIrQsKhBWovA4VuDc4gsLcEFbfFUYA",
        image_type: "original",
        is_primary: true,
      },
    ],
  },
  "prod-6": {
    product_id: "prod-6",
    id: "prod-6",
    artisan_id: "seed-artisan-lakshmi",
    title: "Hand-woven Jute Wall Hanging",
    description: "West Bengal golden jute is hand-spun and knotted by rural artisan women with geometric Scandinavian boho macrame patterns.",
    category: "jute",
    category_label: "Jute & Fiber Art",
    materials: ["100% Raw Golden Jute Fiber", "Unbleached Cotton Cord", "Treated Bamboo Rod"],
    dimensions: "36 inch height × 18 inch width, 550g",
    tags: ["jute", "wallhanging", "boho", "fiberart", "decor", "macrame"],
    price: 2150,
    stock: 7,
    status: "published",
    images: [
      {
        image_id: "img-prod-6",
        id: "img-prod-6",
        product_id: "prod-6",
        image_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDSCTXUc_dz2HlnNtlKLEXF4ty2bwHRYL-qY1osrCgCbk1vogTmu8qPfSWUc6PdJUWJY1loX75tVVzXt7tiMTzGS2A6jX-jgEBGMST3L-IcTnEjScQbIR9w7_W1GMetogzWDNk9vj3Eu_QEOAvokZu-eF2MsE9eHio-PXCBq7-tr1NFV_6YXDgTCjPGqZMGueyd3FEueFF98lk4cEGXOJt4hkcHeRyLbPekwQMnppwdQmm5NKMYS1nuKQ",
        image_type: "original",
        is_primary: true,
      },
    ],
  },
};

export function getSeedProductRecord(productId: string): ProductRecord | null {
  if (!productId) return null;
  return SEED_PRODUCTS_MAP[productId] || null;
}
